window.GAMES = [
  { slug: "2048", name: "2048", category: "Puzzle", featured: true, description: "Merge tiles to reach 2048.", url: "https://play2048.co/" },
  { slug: "hextris", name: "Hextris", category: "Arcade", featured: true, description: "Fast-paced hexagon stacking challenge.", url: "https://hextris.io/" },
  { slug: "cookie-clicker", name: "Cookie Clicker", category: "Idle", featured: true, description: "The classic incremental cookie factory.", url: "https://orteil.dashnet.org/cookieclicker/" },
  { slug: "a-dark-room", name: "A Dark Room", category: "Text", featured: false, description: "Minimalist text survival experience.", url: "https://adarkroom.doublespeakgames.com/" },
  { slug: "qwop", name: "QWOP", category: "Funny", featured: false, description: "Legendary difficult sprint controls.", url: "https://www.foddy.net/Athletics.html" },
  { slug: "tetris", name: "Tetris", category: "Puzzle", featured: true, description: "Classic falling-block puzzle game.", url: "https://tetris.com/play-tetris" },
  { slug: "minesweeper", name: "Minesweeper", category: "Puzzle", featured: false, description: "Clear the board without hitting mines.", url: "https://minesweeperonline.com/" },
  { slug: "sudoku", name: "Web Sudoku", category: "Puzzle", featured: false, description: "Daily sudoku puzzles in-browser.", url: "https://websudoku.com/" },
  { slug: "chess", name: "Lichess", category: "Strategy", featured: true, description: "Play chess vs players or AI.", url: "https://lichess.org/" },
  { slug: "checkers", name: "Checkers", category: "Strategy", featured: false, description: "Quick browser checkers matches.", url: "https://cardgames.io/checkers/" },
  { slug: "connect4", name: "Connect 4", category: "Strategy", featured: false, description: "Classic four-in-a-row battle.", url: "https://www.mathsisfun.com/games/connect4.html" },
  { slug: "slither", name: "Slither.io", category: "Multiplayer", featured: true, description: "Grow your snake and outplay rivals.", url: "https://slither.io/" },
  { slug: "agar", name: "Agar.io", category: "Multiplayer", featured: true, description: "Eat to grow in this online arena.", url: "https://agar.io/" },
  { slug: "krunker", name: "Krunker", category: "Shooter", featured: true, description: "Browser FPS with quick matches.", url: "https://krunker.io/" },
  { slug: "shell-shockers", name: "Shell Shockers", category: "Shooter", featured: false, description: "Egg-themed online FPS action.", url: "https://shellshock.io/" },
  { slug: "drift-hunters", name: "Drift Hunters", category: "Racing", featured: true, description: "Drift-focused 3D driving game.", url: "https://drifthunters2.io/" },
  { slug: "slow-roads", name: "Slow Roads", category: "Racing", featured: false, description: "Relaxed endless driving ride.", url: "https://slowroads.io/" },
  { slug: "geoguessr-free", name: "GeoGuessr Free", category: "Geography", featured: false, description: "Guess locations from street views.", url: "https://www.geoguessr.com/free" },
  { slug: "wordle", name: "Wordle", category: "Word", featured: true, description: "Daily 5-letter word challenge.", url: "https://www.nytimes.com/games/wordle/index.html" },
  { slug: "quordle", name: "Quordle", category: "Word", featured: false, description: "Solve four words at once.", url: "https://www.quordle.com/" },
  { slug: "typeracer", name: "TypeRacer", category: "Skill", featured: false, description: "Race others with typing speed.", url: "https://play.typeracer.com/" },
  { slug: "osu-web", name: "osu! web", category: "Rhythm", featured: false, description: "Rhythm gameplay in browser format.", url: "https://osu.ppy.sh/home" },
  { slug: "pacman", name: "PAC-MAN", category: "Arcade", featured: true, description: "Official PAC-MAN web play.", url: "https://freepacman.org/" },
  { slug: "snake", name: "Snake", category: "Arcade", featured: false, description: "Simple and timeless snake gameplay.", url: "https://playsnake.org/" }
];
